### ISSUE TITLE
[SeaORM docs] clarify PostgreSQL does not support unsigned integers

### ISSUE THREAD

**Issue by billy1624** [SeaQL/seaql.github.io#37]
## Motivation

- Clarify PostgreSQL does not support unsigned integers and migration with column defined in unsigned integer will fallback to signed integers silently
- We can clarify it at https://www.sea-ql.org/SeaORM/docs/generate-entity/entity-structure#column-type

## Additional Information

Context
- https://discord.com/channels/873880840487206962/900758376164757555/993528522280808478

**Comment by penso** [comment]
To clarify the issue, if you use a `u32` as a struct attribute in `Model` and create your migration with a `.unsigned()` it fallbacks as `integer`. When fetching models from the DB those `integer` will be mapped incorrectly and you'll get:

`mismatched types; Rust type core::option::Option<u32> (as SQL type OID) is not compatible with SQL type INT4`

My guess is:
1. Listing converted type per DB type would have helped me finding the issue and I would have seen `pgsql` doesn't support unsigned integer.
2. `DeriveEntityModel` macro should display at least a warning when using `u32` since that can't work.

**Comment by billy1624** [comment]
> 1. Listing converted type per DB type would have helped me finding the issue and I would have seen `pgsql` doesn't support unsigned integer.

Agree! And, I updated https://www.sea-ql.org/SeaORM/docs/generate-entity/entity-structure/#column-type

> 2. `DeriveEntityModel` macro should display at least a warning when using `u32` since that can't work with a pgsql backend. A clear error when used with pgsql would be even better.

This can't be right. At run-time we don't know for sure which database SeaORM will be connected to.

However, with `sea-orm-linter` we could catch that logical error at test-time.
- https://github.com/SeaQL/summer-of-code/discussions/13
P.S. `sea-orm-linter` is under development in this summer.

CC @tyt2y3 @kirawi
